Sailjail validation
sailfishos/sdk-harbour-rpmvalidator pull request #134
Opened 2021-06-22 10:56 UTC by vigejolla

2021-06-22 11:27 UTC, Tomin1 requested changes

2021-06-22 11:27 UTC, Tomin1 commented on rpmvalidation.sh
> +        [[ $value =~ [.] ]] && validation_error "ApplicationName may not contain '.'"
There should be a similar character validation that organization name has. E.g. `[[ ! $value =~ ^[a-z-_][0-9a-z-_]*$ ]]`.

2021-06-22 11:27 UTC, Tomin1 commented on rpmvalidation.sh
> +    if [[ $1 =~ [.][0-9] ]]; then
This checks that later parts don't begin with a number but it doesn't check the very first part.

2021-06-22 11:27 UTC, Tomin1 commented on rpm/sdk-harbour-rpmvalidator.spec
> +install -D -m 0644 disallowed_orgnames.conf %{buildroot}%{_datadir}/%{name}/disallowed_orgnames.conf
I don't see such file here.

2021-06-22 11:36 UTC, vigejolla commented on rpmvalidation.sh
> +        [[ $value =~ [.] ]] && validation_error "ApplicationName may not contain '.'"
The freedesktop spec allows Capital letters in ApplicationName. Should we be more strict in that respect?

2021-06-22 11:37 UTC, Tomin1 commented on rpmvalidation.sh
> +        [[ $value =~ [.] ]] && validation_error "ApplicationName may not contain '.'"
No, we should allow capital letters IMO.

2021-06-22 11:59 UTC, vigejolla commented on rpmvalidation.sh
> +        [[ $value =~ [.] ]] && validation_error "ApplicationName may not contain '.'"
fixed

2021-06-22 11:59 UTC, vigejolla commented on rpmvalidation.sh
> +    if [[ $1 =~ [.][0-9] ]]; then
fixed

2021-06-22 11:59 UTC, vigejolla commented on rpm/sdk-harbour-rpmvalidator.spec
> +install -D -m 0644 disallowed_orgnames.conf %{buildroot}%{_datadir}/%{name}/disallowed_orgnames.conf
forgot to add file... added

2021-06-23 09:08 UTC, Tomin1 commented
I saw some strange things:
If I have an empty X-Sailjail section without anything there, I get this:

> ERROR [/usr/share/applications/mediagallery.desktop] X-Sailjail key is not allowed: 

Seems a little confusing, otherwise doesn't matter very much. An empty section would likely leave the app pretty broken. It's pretty much equivalent to saying that you don't need any directories, D-Bus names (e.g. coveraction) or any permissions but we haven't really thought out if anyone should leave the section empty. We actually use empty Permissions= key ourselves but leaving it out should work the same way.

If I have a permission that is not allowed, I get this:

> Desktop file
> ============
> ERROR [/usr/share/applications/mediagallery.desktop] X-Sailjail permission not allowed: UDisks
> PASSED

So there is an error but it's also PASSED instead of FAILED? The other new error cases result in FAILED.

2021-06-23 09:09 UTC, Tomin1 approved these changes

2021-06-23 09:15 UTC, vigejolla commented
> If I have an empty X-Sailjail section without anything there, I get this:
> 
> ```
> ERROR [/usr/share/applications/mediagallery.desktop] X-Sailjail key is not allowed: 
> ```
> 
> Seems a little confusing, otherwise doesn't matter very much. An empty section would likely leave the app pretty broken. It's pretty much equivalent to saying that you don't need any directories, D-Bus names (e.g. coveraction) or any permissions but we haven't really thought out if anyone should leave the section empty. We actually use empty Permissions= key ourselves but leaving it out should work the same way.

I think we should not allow empty X-Sailjail section, at the minimum it should be:

    [X-Sailjail]
    Permissions=

I'll fix the error message

> Desktop file
> ============
> ERROR [/usr/share/applications/mediagallery.desktop] X-Sailjail permission not allowed: UDisks
> PASSED

I thought I fixed this already, but I guess not then.

2021-06-23 09:39 UTC, vigejolla commented
> > # Desktop file
> > ERROR [/usr/share/applications/mediagallery.desktop] X-Sailjail permission not allowed: UDisks
> > PASSED
> 
> I thought I fixed this already, but I guess not then.

Yes, I indeed had fixed this already. Are you sure you were testing with the latest version?

2021-06-23 10:17 UTC, Tomin1 approved these changes
LGTM.

2021-06-23 10:18 UTC, merged

2021-08-05 13:29 UTC, HengYeDev commented
Does this mean that the program can write to config/OrganizationName/AppName

2021-09-01 04:40 UTC, vigejolla commented
> Does this mean that the program can write to config/OrganizationName/AppName

Sorry for the late reply. That's indeed the idea.