Generating allowed lists in Markdown
sailfishos/sdk-harbour-rpmvalidator pull request #144
Opened 2021-11-26 08:44 UTC by vigejolla

2021-11-26 09:24 UTC, Thaodan commented
Should the *.conf files be in the tree if the are generated during build?

2021-11-26 12:37 UTC, vigejolla commented
> Should the *.conf files be in the tree if the are generated during build?

They are not generated during build

2021-11-29 06:58 UTC, sledges requested changes
`->` looks like a sneaked-in typo: https://github.com/sailfishos/sdk-harbour-rpmvalidator/blob/7125b42afbf81817cc77d2545ec3363fa8b8bba7/allowed_qmlimports.conf#L38

2021-11-29 06:58 UTC, sledges commented on allowed_libraries.conf
> +# First line of comment block is used as header in documentation
Should this comment be also in other .conf files where applicable?

2021-11-29 06:58 UTC, sledges commented on allowed_libraries.conf
>  # Pattern matching is supported as withing BASH shell with 'extglob' enabled.
```suggestion
# Pattern matching is supported as within BASH shell with 'extglob' enabled.
```
Looks like an old typo:)

2021-11-29 06:59 UTC, vigejolla commented on allowed_libraries.conf
> +# First line of comment block is used as header in documentation
Probably :)

2021-11-29 07:09 UTC, vigejolla commented on allowed_libraries.conf
> +# First line of comment block is used as header in documentation
Added

2021-11-29 07:10 UTC, vigejolla commented on allowed_libraries.conf
>  # Pattern matching is supported as withing BASH shell with 'extglob' enabled.
fixed

2021-11-29 07:12 UTC, vigejolla commented
> `->` looks like a sneaked-in typo:
> 
> https://github.com/sailfishos/sdk-harbour-rpmvalidator/blob/7125b42afbf81817cc77d2545ec3363fa8b8bba7/allowed_qmlimports.conf#L38

That was sneaky!

2021-11-29 07:14 UTC, vigejolla commented
> > `->` looks like a sneaked-in typo:
> > https://github.com/sailfishos/sdk-harbour-rpmvalidator/blob/7125b42afbf81817cc77d2545ec3363fa8b8bba7/allowed_qmlimports.conf#L38
> 
> That was sneaky!

fixed now as well

2021-11-29 07:55 UTC, sledges approved these changes

2021-11-29 08:53 UTC, sledges commented on doc/base.md
> +    - ${subsection[0]}
this results in extra leading space, due to untrimmed `${subsection[0]}`

2021-11-29 11:08 UTC, vigejolla commented on doc/base.md
> +    - ${subsection[0]}
Fixed; now the strings are trimmed

2021-11-29 11:09 UTC, merged